spring:
  datasource:
    url: jdbc:h2:mem:test
    username: myuser
    password: mypassword
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/master"
server:
  port: 8180